######################################################################
# Automatically generated by qmake (2.01a) Wed May 22 17:35:50 2013
######################################################################
#TEMPLATE = app
TEMPLATE = lib
TARGET = InPut
#DEPENDPATH += . GeneratedFiles
#INCLUDEPATH += . GeneratedFiles

# Input
HEADERS += keyboard.h \
    inputmethod.h \
    formhanzitable.h \
    HanziManager.h \
    formnumpad.h \
    padbase.h \
    formsymbolpad.h \
    formhanziselector.h \
    keyboardinput.h \
    mainwindow.h

FORMS += keyboard.ui \
    formhanzitable.ui \
    formnumpad.ui \
    formsymbolpad.ui \
    formhanziselector.ui \
    mainwindow.ui

SOURCES += keyboard.cpp \
           inputmethod.cpp \
    formhanzitable.cpp \
    HanziManager.cpp \
    formnumpad.cpp \
    padbase.cpp \
    formsymbolpad.cpp \
    formhanziselector.cpp \
    keyboardinput.cpp \
    mainwindow.cpp \
    main.cpp

RESOURCES += keypad.qrc

#linux-g++ {
#    QMAKE_CXXFLAGS += -std=C++0x
#}
